from django.core.management.base import BaseCommand
from taxi.models import TransportRoute


class Command(BaseCommand):
    help = "Seed transport routes for Kenya and Tanzania"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Clear existing routes before seeding",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            deleted_count = TransportRoute.objects.all().delete()[0]
            self.stdout.write(self.style.WARNING(f"Deleted {deleted_count} existing routes"))

        kenya_routes = [
            # Airport Transfers
            {
                "country": "Kenya",
                "route_category": "Airport Transfer",
                "origin": "Moi International Airport",
                "destination": "Nyali",
                "transport_type": "Taxi",
                "estimated_time": "20-35 mins",
                "price_min": 1200,
                "price_max": 2500,
                "currency": "KES",
                "notes": "Good for hotels, apartments and beach stays in Nyali.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Airport Transfer",
                "origin": "Moi International Airport",
                "destination": "Bamburi",
                "transport_type": "Taxi",
                "estimated_time": "30-45 mins",
                "price_min": 1800,
                "price_max": 3500,
                "currency": "KES",
                "notes": "Useful for budget hotels, BnBs and beach stays.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Airport Transfer",
                "origin": "Moi International Airport",
                "destination": "Shanzu",
                "transport_type": "Taxi",
                "estimated_time": "40-60 mins",
                "price_min": 2500,
                "price_max": 4500,
                "currency": "KES",
                "notes": "Best for beach resorts and serviced apartments.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Airport Transfer",
                "origin": "Moi International Airport",
                "destination": "Diani",
                "transport_type": "Taxi/Ferry Transfer",
                "estimated_time": "1.5-2.5 hrs",
                "price_min": 5000,
                "price_max": 9000,
                "currency": "KES",
                "notes": "Route may involve Likoni Ferry depending on traffic.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Airport Transfer",
                "origin": "Moi International Airport",
                "destination": "Mtwapa",
                "transport_type": "Taxi",
                "estimated_time": "45-70 mins",
                "price_min": 2500,
                "price_max": 5000,
                "currency": "KES",
                "notes": "Common for nightlife, apartments and long stays.",
                "is_featured": True,
            },
            # Rail Transfers
            {
                "country": "Kenya",
                "route_category": "Rail Transfer",
                "origin": "Mombasa SGR Terminus",
                "destination": "Nyali",
                "transport_type": "Taxi",
                "estimated_time": "30-45 mins",
                "price_min": 1800,
                "price_max": 3500,
                "currency": "KES",
                "notes": "Suitable for guests arriving by SGR.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Rail Transfer",
                "origin": "Mombasa SGR Terminus",
                "destination": "Bamburi",
                "transport_type": "Taxi",
                "estimated_time": "40-60 mins",
                "price_min": 2500,
                "price_max": 4000,
                "currency": "KES",
                "notes": "Good for North Coast stays.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Rail Transfer",
                "origin": "Mombasa SGR Terminus",
                "destination": "Shanzu",
                "transport_type": "Taxi",
                "estimated_time": "50-75 mins",
                "price_min": 3000,
                "price_max": 5000,
                "currency": "KES",
                "notes": "Best for beach resort transfers.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Rail Transfer",
                "origin": "Mombasa SGR Terminus",
                "destination": "Diani",
                "transport_type": "Taxi/Ferry Transfer",
                "estimated_time": "2-3 hrs",
                "price_min": 6000,
                "price_max": 10000,
                "currency": "KES",
                "notes": "Common tourist route from SGR to South Coast.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Rail Transfer",
                "origin": "Mombasa SGR Terminus",
                "destination": "Mtwapa",
                "transport_type": "Taxi",
                "estimated_time": "50-75 mins",
                "price_min": 3000,
                "price_max": 5000,
                "currency": "KES",
                "notes": "Useful for apartments and nightlife stays.",
                "is_featured": False,
            },
            # Ferry Guide
            {
                "country": "Kenya",
                "route_category": "Ferry Guide",
                "origin": "Likoni Ferry",
                "destination": "Diani",
                "transport_type": "Taxi/Matatu",
                "estimated_time": "45-90 mins",
                "price_min": 300,
                "price_max": 3000,
                "currency": "KES",
                "notes": "Budget users may use matatu; tourists may prefer private taxi.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Ferry Guide",
                "origin": "Likoni Ferry",
                "destination": "Tiwi",
                "transport_type": "Taxi",
                "estimated_time": "35-60 mins",
                "price_min": 2000,
                "price_max": 4000,
                "currency": "KES",
                "notes": "Quiet South Coast beach route.",
                "is_featured": False,
            },
            {
                "country": "Kenya",
                "route_category": "Ferry Guide",
                "origin": "Likoni Ferry",
                "destination": "Ukunda",
                "transport_type": "Taxi/Matatu",
                "estimated_time": "45-75 mins",
                "price_min": 300,
                "price_max": 2500,
                "currency": "KES",
                "notes": "Ukunda is the main access town for Diani.",
                "is_featured": True,
            },
            # Beach Transfers
            {
                "country": "Kenya",
                "route_category": "Beach Transfer",
                "origin": "Diani",
                "destination": "Shimoni",
                "transport_type": "Taxi",
                "estimated_time": "1.5-2 hrs",
                "price_min": 5000,
                "price_max": 9000,
                "currency": "KES",
                "notes": "Gateway to Wasini Island and Kisite Marine Park.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Beach Transfer",
                "origin": "Diani",
                "destination": "Wasini Island Jetty",
                "transport_type": "Taxi + Boat",
                "estimated_time": "2-3 hrs",
                "price_min": 6000,
                "price_max": 12000,
                "currency": "KES",
                "notes": "Useful for marine tours and dolphin excursions.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Beach Transfer",
                "origin": "Diani",
                "destination": "Chale Island",
                "transport_type": "Taxi/Resort Transfer",
                "estimated_time": "45-75 mins",
                "price_min": 4000,
                "price_max": 8000,
                "currency": "KES",
                "notes": "Popular for honeymoon and luxury stays.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Beach Transfer",
                "origin": "Diani",
                "destination": "Msambweni",
                "transport_type": "Taxi",
                "estimated_time": "45-70 mins",
                "price_min": 3500,
                "price_max": 7000,
                "currency": "KES",
                "notes": "Quiet beach and luxury villa area.",
                "is_featured": False,
            },
            # North Coast Transfers
            {
                "country": "Kenya",
                "route_category": "North Coast Transfer",
                "origin": "Mombasa CBD",
                "destination": "Watamu",
                "transport_type": "Taxi/Private Transfer",
                "estimated_time": "2-2.5 hrs",
                "price_min": 8000,
                "price_max": 14000,
                "currency": "KES",
                "notes": "Popular for beach holidays and marine park visits.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "North Coast Transfer",
                "origin": "Mombasa CBD",
                "destination": "Malindi",
                "transport_type": "Taxi/Private Transfer",
                "estimated_time": "2.5-3 hrs",
                "price_min": 9000,
                "price_max": 16000,
                "currency": "KES",
                "notes": "Good for beach and heritage tourism.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "North Coast Transfer",
                "origin": "Mombasa CBD",
                "destination": "Kilifi",
                "transport_type": "Taxi/Private Transfer",
                "estimated_time": "1.5-2 hrs",
                "price_min": 5000,
                "price_max": 9000,
                "currency": "KES",
                "notes": "Good for creek stays and beach lodges.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "North Coast Transfer",
                "origin": "Mombasa CBD",
                "destination": "Vipingo",
                "transport_type": "Taxi",
                "estimated_time": "1-1.5 hrs",
                "price_min": 4000,
                "price_max": 7500,
                "currency": "KES",
                "notes": "Useful for villas, golf and resort stays.",
                "is_featured": False,
            },
            # Island Transfers
            {
                "country": "Kenya",
                "route_category": "Island Transfer",
                "origin": "Mombasa",
                "destination": "Lamu",
                "transport_type": "Flight/Bus + Boat",
                "estimated_time": "Variable",
                "price_min": 6000,
                "price_max": 18000,
                "currency": "KES",
                "notes": "Use for Lamu Town, Shela and Manda Island travel planning.",
                "is_featured": True,
            },
            {
                "country": "Kenya",
                "route_category": "Island Transfer",
                "origin": "Lamu Airport",
                "destination": "Shela",
                "transport_type": "Boat Transfer",
                "estimated_time": "15-30 mins",
                "price_min": 500,
                "price_max": 2500,
                "currency": "KES",
                "notes": "Common route for Shela beach stays.",
                "is_featured": True,
            },
        ]

        tanzania_routes = [
            # Airport Transfers
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Zanzibar Airport",
                "destination": "Stone Town",
                "transport_type": "Taxi",
                "estimated_time": "15-25 mins",
                "price_min": 10,
                "price_max": 25,
                "currency": "USD",
                "notes": "Good for heritage hotels and city stays.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Zanzibar Airport",
                "destination": "Nungwi",
                "transport_type": "Taxi/Shuttle",
                "estimated_time": "1.5-2 hrs",
                "price_min": 35,
                "price_max": 70,
                "currency": "USD",
                "notes": "Popular beach and nightlife destination.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Zanzibar Airport",
                "destination": "Kendwa",
                "transport_type": "Taxi/Shuttle",
                "estimated_time": "1.5-2 hrs",
                "price_min": 35,
                "price_max": 70,
                "currency": "USD",
                "notes": "Good for beach resorts and sunset stays.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Zanzibar Airport",
                "destination": "Paje",
                "transport_type": "Taxi/Shuttle",
                "estimated_time": "1-1.5 hrs",
                "price_min": 30,
                "price_max": 60,
                "currency": "USD",
                "notes": "Popular for kitesurfing and beach stays.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Zanzibar Airport",
                "destination": "Jambiani",
                "transport_type": "Taxi/Shuttle",
                "estimated_time": "1.25-1.75 hrs",
                "price_min": 35,
                "price_max": 65,
                "currency": "USD",
                "notes": "Quiet beach and local culture destination.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Zanzibar Airport",
                "destination": "Matemwe",
                "transport_type": "Taxi/Shuttle",
                "estimated_time": "1.25-1.75 hrs",
                "price_min": 35,
                "price_max": 65,
                "currency": "USD",
                "notes": "Good for quiet beach resorts.",
                "is_featured": False,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Zanzibar Airport",
                "destination": "Kiwengwa",
                "transport_type": "Taxi/Shuttle",
                "estimated_time": "45-75 mins",
                "price_min": 30,
                "price_max": 55,
                "currency": "USD",
                "notes": "Popular resort beach area.",
                "is_featured": False,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Zanzibar Airport",
                "destination": "Fumba",
                "transport_type": "Taxi",
                "estimated_time": "30-45 mins",
                "price_min": 20,
                "price_max": 45,
                "currency": "USD",
                "notes": "Luxury and waterfront stays.",
                "is_featured": False,
            },
            # Ferry Transfers
            {
                "country": "Tanzania",
                "route_category": "Ferry Transfer",
                "origin": "Zanzibar Ferry Port",
                "destination": "Stone Town Hotels",
                "transport_type": "Taxi/Walk",
                "estimated_time": "5-15 mins",
                "price_min": 5,
                "price_max": 15,
                "currency": "USD",
                "notes": "Many Stone Town hotels are close to the ferry area.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Ferry Transfer",
                "origin": "Zanzibar Ferry Port",
                "destination": "Nungwi",
                "transport_type": "Taxi/Shuttle",
                "estimated_time": "1.5-2 hrs",
                "price_min": 35,
                "price_max": 70,
                "currency": "USD",
                "notes": "Useful for tourists arriving by ferry from Dar.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Ferry Transfer",
                "origin": "Zanzibar Ferry Port",
                "destination": "Paje",
                "transport_type": "Taxi/Shuttle",
                "estimated_time": "1-1.5 hrs",
                "price_min": 30,
                "price_max": 60,
                "currency": "USD",
                "notes": "Good for beach and kitesurfing stays.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Ferry Transfer",
                "origin": "Zanzibar Ferry Port",
                "destination": "Kendwa",
                "transport_type": "Taxi/Shuttle",
                "estimated_time": "1.5-2 hrs",
                "price_min": 35,
                "price_max": 70,
                "currency": "USD",
                "notes": "Popular beach transfer route.",
                "is_featured": True,
            },
            # Dar es Salaam Airport Transfers
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Julius Nyerere International Airport",
                "destination": "Dar es Salaam City Centre",
                "transport_type": "Taxi",
                "estimated_time": "25-60 mins",
                "price_min": 30000,
                "price_max": 70000,
                "currency": "TZS",
                "notes": "Time varies heavily with traffic.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Julius Nyerere International Airport",
                "destination": "Masaki",
                "transport_type": "Taxi",
                "estimated_time": "45-90 mins",
                "price_min": 50000,
                "price_max": 100000,
                "currency": "TZS",
                "notes": "Executive apartments, hotels and nightlife.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Julius Nyerere International Airport",
                "destination": "Oyster Bay",
                "transport_type": "Taxi",
                "estimated_time": "45-90 mins",
                "price_min": 50000,
                "price_max": 100000,
                "currency": "TZS",
                "notes": "Good for business and leisure stays.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Julius Nyerere International Airport",
                "destination": "Mikocheni",
                "transport_type": "Taxi",
                "estimated_time": "40-80 mins",
                "price_min": 45000,
                "price_max": 90000,
                "currency": "TZS",
                "notes": "Popular for apartments and longer stays.",
                "is_featured": False,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Julius Nyerere International Airport",
                "destination": "Msasani",
                "transport_type": "Taxi",
                "estimated_time": "45-90 mins",
                "price_min": 50000,
                "price_max": 100000,
                "currency": "TZS",
                "notes": "Good for apartments and nightlife.",
                "is_featured": False,
            },
            {
                "country": "Tanzania",
                "route_category": "Airport Transfer",
                "origin": "Julius Nyerere International Airport",
                "destination": "Kigamboni",
                "transport_type": "Taxi/Ferry or Bridge Route",
                "estimated_time": "45-100 mins",
                "price_min": 50000,
                "price_max": 110000,
                "currency": "TZS",
                "notes": "Beach and family stay area.",
                "is_featured": True,
            },
            # Ferry Routes
            {
                "country": "Tanzania",
                "route_category": "Ferry Route",
                "origin": "Dar es Salaam Ferry Terminal",
                "destination": "Zanzibar Ferry Port",
                "transport_type": "Ferry",
                "estimated_time": "1.5-2.5 hrs",
                "price_min": 35,
                "price_max": 60,
                "currency": "USD",
                "notes": "Core tourist route between mainland Tanzania and Zanzibar.",
                "is_featured": True,
            },
            # City Transfers
            {
                "country": "Tanzania",
                "route_category": "City Transfer",
                "origin": "Dar es Salaam City Centre",
                "destination": "Masaki",
                "transport_type": "Taxi",
                "estimated_time": "20-45 mins",
                "price_min": 20000,
                "price_max": 50000,
                "currency": "TZS",
                "notes": "Useful for executive hotels and apartments.",
                "is_featured": False,
            },
            {
                "country": "Tanzania",
                "route_category": "City Transfer",
                "origin": "Dar es Salaam City Centre",
                "destination": "Coco Beach",
                "transport_type": "Taxi",
                "estimated_time": "20-45 mins",
                "price_min": 20000,
                "price_max": 50000,
                "currency": "TZS",
                "notes": "Popular leisure route.",
                "is_featured": False,
            },
            {
                "country": "Tanzania",
                "route_category": "City Transfer",
                "origin": "Dar es Salaam City Centre",
                "destination": "Kigamboni",
                "transport_type": "Taxi/Ferry",
                "estimated_time": "30-75 mins",
                "price_min": 25000,
                "price_max": 70000,
                "currency": "TZS",
                "notes": "Beach and family day trip area.",
                "is_featured": True,
            },
            # Island Day Trips
            {
                "country": "Tanzania",
                "route_category": "Island Day Trip",
                "origin": "Dar es Salaam",
                "destination": "Mbudya Island",
                "transport_type": "Taxi + Boat",
                "estimated_time": "1-2 hrs",
                "price_min": 30000,
                "price_max": 90000,
                "currency": "TZS",
                "notes": "Good for beach day trips.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Island Day Trip",
                "origin": "Dar es Salaam",
                "destination": "Bongoyo Island",
                "transport_type": "Taxi + Boat",
                "estimated_time": "1-2 hrs",
                "price_min": 30000,
                "price_max": 90000,
                "currency": "TZS",
                "notes": "Popular day-trip island.",
                "is_featured": True,
            },
            # Coastal Transfers
            {
                "country": "Tanzania",
                "route_category": "Coastal Transfer",
                "origin": "Dar es Salaam",
                "destination": "Bagamoyo",
                "transport_type": "Taxi/Private Transfer",
                "estimated_time": "1.5-2.5 hrs",
                "price_min": 100000,
                "price_max": 220000,
                "currency": "TZS",
                "notes": "Historic coastal town and beach resorts.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Coastal Transfer",
                "origin": "Dar es Salaam",
                "destination": "Saadani National Park",
                "transport_type": "Private Transfer",
                "estimated_time": "3.5-5 hrs",
                "price_min": 250000,
                "price_max": 500000,
                "currency": "TZS",
                "notes": "Beach and safari combination.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Coastal Transfer",
                "origin": "Dar es Salaam",
                "destination": "Tanga",
                "transport_type": "Bus/Private Transfer",
                "estimated_time": "5-7 hrs",
                "price_min": 30000,
                "price_max": 350000,
                "currency": "TZS",
                "notes": "Coastal city and gateway to Pangani.",
                "is_featured": False,
            },
            {
                "country": "Tanzania",
                "route_category": "Coastal Transfer",
                "origin": "Tanga Town",
                "destination": "Pangani",
                "transport_type": "Taxi/Private Transfer",
                "estimated_time": "1.5-2 hrs",
                "price_min": 80000,
                "price_max": 180000,
                "currency": "TZS",
                "notes": "Beach and heritage destination.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Coastal Transfer",
                "origin": "Pangani",
                "destination": "Ushongo Beach",
                "transport_type": "Taxi",
                "estimated_time": "20-40 mins",
                "price_min": 30000,
                "price_max": 70000,
                "currency": "TZS",
                "notes": "Quiet beach stay route.",
                "is_featured": False,
            },
            # Island Transfers
            {
                "country": "Tanzania",
                "route_category": "Island Transfer",
                "origin": "Mafia Island Airport",
                "destination": "Kilindoni",
                "transport_type": "Taxi",
                "estimated_time": "10-20 mins",
                "price_min": 10000,
                "price_max": 30000,
                "currency": "TZS",
                "notes": "Main town transfer on Mafia Island.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Island Transfer",
                "origin": "Mafia Island Airport",
                "destination": "Utende",
                "transport_type": "Taxi",
                "estimated_time": "30-45 mins",
                "price_min": 40000,
                "price_max": 90000,
                "currency": "TZS",
                "notes": "Gateway to Mafia Island Marine Park.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Island Transfer",
                "origin": "Kilindoni",
                "destination": "Mafia Island Marine Park",
                "transport_type": "Taxi",
                "estimated_time": "30-45 mins",
                "price_min": 40000,
                "price_max": 90000,
                "currency": "TZS",
                "notes": "Diving and snorkeling destination.",
                "is_featured": True,
            },
            # Southern Coast Transfers
            {
                "country": "Tanzania",
                "route_category": "Southern Coast Transfer",
                "origin": "Mtwara Airport",
                "destination": "Mtwara Town",
                "transport_type": "Taxi",
                "estimated_time": "15-25 mins",
                "price_min": 15000,
                "price_max": 40000,
                "currency": "TZS",
                "notes": "Business and coastal stay transfer.",
                "is_featured": False,
            },
            {
                "country": "Tanzania",
                "route_category": "Southern Coast Transfer",
                "origin": "Mtwara Town",
                "destination": "Mikindani",
                "transport_type": "Taxi",
                "estimated_time": "20-35 mins",
                "price_min": 20000,
                "price_max": 50000,
                "currency": "TZS",
                "notes": "Historic coastal town.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Southern Coast Transfer",
                "origin": "Mtwara Town",
                "destination": "Mnazi Bay",
                "transport_type": "Private Transfer",
                "estimated_time": "1-2 hrs",
                "price_min": 80000,
                "price_max": 180000,
                "currency": "TZS",
                "notes": "Marine and eco-tourism route.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Southern Coast Transfer",
                "origin": "Lindi Town",
                "destination": "Kilwa Masoko",
                "transport_type": "Private Transfer",
                "estimated_time": "3-4.5 hrs",
                "price_min": 180000,
                "price_max": 350000,
                "currency": "TZS",
                "notes": "Gateway to Kilwa heritage sites.",
                "is_featured": True,
            },
            {
                "country": "Tanzania",
                "route_category": "Southern Coast Transfer",
                "origin": "Kilwa Masoko",
                "destination": "Kilwa Kisiwani",
                "transport_type": "Boat Transfer",
                "estimated_time": "20-45 mins",
                "price_min": 30000,
                "price_max": 100000,
                "currency": "TZS",
                "notes": "UNESCO heritage excursion route.",
                "is_featured": True,
            },
        ]

        all_routes = kenya_routes + tanzania_routes

        created_count = 0
        for route_data in all_routes:
            TransportRoute.objects.create(**route_data)
            created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully seeded {created_count} transport routes "
                f"({len(kenya_routes)} Kenya, {len(tanzania_routes)} Tanzania)"
            )
        )
