# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("payment_reference", models.CharField(blank=True, max_length=100, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bookings", to="properties.property")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bookings", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="availability", to="properties.property")),
            ],
            options={
                "verbose_name_plural": "Availabilities",
                "ordering": ["date"],
            },
        ),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.UniqueConstraint(fields=("property", "date"), name="unique_property_date"),
        ),
        migrations.AddIndex(
            model_name="availability",
            index=models.Index(fields=["property", "date"], name="bookings_av_property_6a0a0d_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_bo_status_7b7d2a_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["user", "status"], name="bookings_bo_user_id_8c9e3f_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["property", "status"], name="bookings_bo_property_1a2b3c_idx"),
        ),
    ]
