# Generated by Django 4.2.28 on 2026-04-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='availability',
            new_name='bookings_av_propert_3efa20_idx',
            old_name='bookings_av_property_6a0a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_status_233e96_idx',
            old_name='bookings_bo_status_7b7d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_user_id_69a5d5_idx',
            old_name='bookings_bo_user_id_8c9e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_propert_92bdff_idx',
            old_name='bookings_bo_property_1a2b3c_idx',
        ),
    ]
