# Generated by Django 4.2.30 on 2026-05-14 20:03

import billing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0009_property_base_currency_property_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa Till'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], default='mpesa', max_length=20)),
                ('reference_number', models.CharField(help_text='M-Pesa transaction code or Bank Ref', max_length=100)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='billing/receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='Notes from admin upon verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_value', models.DecimalField(decimal_places=2, help_text='Total value of the booking', max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Percentage rate, e.g., 10.00', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Amount owed to MakaziPlus', max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('disputed', 'Disputed'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField(default=billing.models.default_due_date)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
