# Generated by Django 4.2.28 on 2026-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('package_type', models.CharField(choices=[('airport-pickup-stay', 'Airport Pickup + Stay'), ('beach-holiday-packages', 'Beach Holiday Packages'), ('family-vacation-packages', 'Family Vacation Packages'), ('honeymoon-packages', 'Honeymoon Packages'), ('weekend-getaways', 'Weekend Getaways'), ('executive-business-stay', 'Executive Business Stay'), ('student-budget-packages', 'Student Budget Packages'), ('zanzibar-ferry-stay', 'Zanzibar Ferry + Stay'), ('mombasa-sgr-stay', 'Mombasa SGR + Stay')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_label', models.CharField(blank=True, default='', max_length=80)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('includes', models.TextField(blank=True, default='')),
                ('transport_included', models.BooleanField(default=False)),
                ('meals_included', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
