# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title_sw", models.CharField(max_length=255)),
                ("description_sw", models.TextField(blank=True)),
                ("location", models.CharField(max_length=255)),
                ("price_per_night", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rules_sw", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("host", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="properties", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="properties/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="properties.property")),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
