# Generated by Django 4.2.28 on 2026-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='catalog_slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('bnb', 'BnB'), ('hotel', 'Hotel'), ('villa', 'Villa')], default='house', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='property',
            name='town',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
