# Generated by Django 4.2.28 on 2026-04-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('properties', '0003_property_amenities_property_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='destinations.destination'),
        ),
    ]
