# Generated by Django 4.2.30 on 2026-05-14 19:31

from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_seed_stay_types_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='base_currency',
            field=models.CharField(default='KES', help_text='ISO currency code for the listed price (KES, TZS, USD, etc.)', max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('bnb', 'BnB'), ('hotel', 'Hotel'), ('villa', 'Villa')], default='house', help_text='[DEPRECATED] Use category + property_type instead.', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, default='', help_text='Upload MP4/MOV (max 100 MB). Or use the external_url field for YouTube/Drive links.', upload_to=properties.models.property_video_upload_to)),
                ('external_url', models.URLField(blank=True, default='', help_text='YouTube, Google Drive or other shareable video link.')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
