# Generated by Django 4.2.30 on 2026-05-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0009_property_base_currency_property_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant Delivery'), ('grocery', 'Grocery Delivery'), ('pharmacy', 'Pharmacy & Essentials'), ('all_in_one', 'All-in-One Delivery')], max_length=50)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('referral_link', models.URLField(blank=True, help_text='Link to open the partner app/website', null=True)),
                ('status', models.BooleanField(default=True, help_text='Is this partner currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(help_text='City or specific neighborhood', max_length=255)),
                ('delivery_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_sponsored', models.BooleanField(default=False, help_text='Featured placement for monetization')),
                ('whatsapp_number', models.CharField(blank=True, help_text='For direct local ordering', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='services.deliverypartner')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDeliveryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.deliverypartner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_options', to='properties.property')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.restaurant')),
            ],
            options={
                'unique_together': {('property', 'restaurant'), ('property', 'partner')},
            },
        ),
    ]
