from django.db import migrations, models


TRANSPORT_ROUTE_SQL = """
CREATE TABLE IF NOT EXISTS taxi_transportroute (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country varchar(100) NOT NULL,
    route_category varchar(100) NOT NULL,
    origin varchar(150) NOT NULL,
    destination varchar(150) NOT NULL,
    transport_type varchar(100) NOT NULL,
    estimated_time varchar(100) NOT NULL,
    price_min numeric(10, 2) NULL,
    price_max numeric(10, 2) NULL,
    currency varchar(20) NOT NULL,
    notes text NOT NULL,
    is_featured boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS taxi_tr_country_idx ON taxi_transportroute (country, is_active);
CREATE INDEX IF NOT EXISTS taxi_tr_origin_idx ON taxi_transportroute (origin, destination);
CREATE INDEX IF NOT EXISTS taxi_tr_feature_idx ON taxi_transportroute (is_featured, is_active);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0002_taxibooking_estimated_price_taxibooking_return_trip_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=TRANSPORT_ROUTE_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="TransportRoute",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("country", models.CharField(max_length=100)),
                        (
                            "route_category",
                            models.CharField(
                                choices=[
                                    ("Airport Transfer", "Airport Transfer"),
                                    ("Rail Transfer", "Rail Transfer"),
                                    ("Ferry Guide", "Ferry Guide"),
                                    ("Ferry Transfer", "Ferry Transfer"),
                                    ("Ferry Route", "Ferry Route"),
                                    ("Beach Transfer", "Beach Transfer"),
                                    ("North Coast Transfer", "North Coast Transfer"),
                                    ("Island Transfer", "Island Transfer"),
                                    ("City Transfer", "City Transfer"),
                                    ("Island Day Trip", "Island Day Trip"),
                                    ("Coastal Transfer", "Coastal Transfer"),
                                    ("Southern Coast Transfer", "Southern Coast Transfer"),
                                ],
                                max_length=100,
                            ),
                        ),
                        ("origin", models.CharField(max_length=150)),
                        ("destination", models.CharField(max_length=150)),
                        (
                            "transport_type",
                            models.CharField(
                                choices=[
                                    ("Taxi", "Taxi"),
                                    ("Taxi/Ferry Transfer", "Taxi/Ferry Transfer"),
                                    ("Taxi/Matatu", "Taxi/Matatu"),
                                    ("Taxi + Boat", "Taxi + Boat"),
                                    ("Taxi/Resort Transfer", "Taxi/Resort Transfer"),
                                    ("Taxi/Private Transfer", "Taxi/Private Transfer"),
                                    ("Private Transfer", "Private Transfer"),
                                    ("Taxi/Shuttle", "Taxi/Shuttle"),
                                    ("Taxi/Walk", "Taxi/Walk"),
                                    ("Ferry", "Ferry"),
                                    ("Bus/Private Transfer", "Bus/Private Transfer"),
                                    ("Boat Transfer", "Boat Transfer"),
                                    ("Flight/Bus + Boat", "Flight/Bus + Boat"),
                                ],
                                max_length=100,
                            ),
                        ),
                        ("estimated_time", models.CharField(blank=True, max_length=100)),
                        ("price_min", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                        ("price_max", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                        ("currency", models.CharField(default="KES", max_length=20)),
                        ("notes", models.TextField(blank=True)),
                        ("is_featured", models.BooleanField(default=False)),
                        ("is_active", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "ordering": ["country", "route_category", "origin"],
                        "indexes": [
                            models.Index(fields=["country", "is_active"], name="taxi_tr_country_idx"),
                            models.Index(fields=["origin", "destination"], name="taxi_tr_origin_idx"),
                            models.Index(fields=["is_featured", "is_active"], name="taxi_tr_feature_idx"),
                        ],
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportPartner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("ride_app", "Ride App"),
                            ("airport_transfer", "Airport Transfer"),
                            ("private_transfer", "Private Transfer"),
                            ("local_taxi", "Local Taxi"),
                            ("tour_transfer", "Tour Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("booking_url", models.URLField(blank=True)),
                ("whatsapp_number", models.CharField(blank=True, max_length=30)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_external", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(fields=["active", "is_featured"], name="taxi_tp_active_idx"),
                    models.Index(fields=["region", "city"], name="taxi_tp_region_idx"),
                    models.Index(fields=["service_type", "active"], name="taxi_tp_service_idx"),
                ],
            },
        ),
    ]
