# Generated by Django 4.2.30 on 2026-05-31 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('FOOD', 'Food Service'), ('DELIVERY', 'Delivery Partner'), ('BUSINESS', 'Business Service')], max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=50)),
                ('location', models.CharField(help_text='City, region, or specific area of operation', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('id_document', models.FileField(blank=True, help_text='National ID or Passport', null=True, upload_to='providers/documents/id/')),
                ('business_document', models.FileField(blank=True, help_text='Business registration documents (if applicable)', null=True, upload_to='providers/documents/business/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
