# Generated by Django 4.2.28 on 2026-04-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('destination_name', models.CharField(max_length=150)),
                ('destination_slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('destination_type', models.CharField(blank=True, default='', max_length=100)),
                ('tourism_category', models.CharField(blank=True, default='', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country', 'region', 'destination_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(fields=('country', 'region', 'destination_name'), name='unique_destination_per_region'),
        ),
    ]
