# Generated by Django 4.2.30 on 2026-05-14 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending_verification', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('create_admins', 'Create Admins'), ('manage_users', 'Manage Users'), ('view_users', 'View Users'), ('delete_users', 'Delete Users'), ('verify_agents', 'Verify Agents'), ('verify_owners', 'Verify House Owners'), ('verify_hotels', 'Verify Hotels/BnBs'), ('verify_taxi', 'Verify Taxi Providers'), ('reject_verification', 'Reject Verification'), ('approve_listings', 'Approve Listings'), ('reject_listings', 'Reject Listings'), ('edit_any_listing', 'Edit Any Listing'), ('delete_listings', 'Delete Listings'), ('feature_listings', 'Feature Listings'), ('view_all_listings', 'View All Listings'), ('manage_own_listings', 'Manage Own Listings'), ('view_all_bookings', 'View All Bookings'), ('manage_bookings', 'Manage Bookings'), ('cancel_bookings', 'Cancel Bookings'), ('view_own_bookings', 'View Own Bookings'), ('view_all_payments', 'View All Payments'), ('manage_payments', 'Manage Payments'), ('approve_refunds', 'Approve Refunds'), ('manage_payouts', 'Manage Payouts'), ('set_commissions', 'Set Commissions'), ('view_own_payments', 'View Own Payments'), ('view_tickets', 'View Support Tickets'), ('respond_tickets', 'Respond to Tickets'), ('escalate_disputes', 'Escalate Disputes'), ('manage_ai_content', 'Manage AI Content'), ('manage_knowledge_base', 'Manage Knowledge Base'), ('manage_destinations', 'Manage Destinations'), ('manage_routes', 'Manage Transport Routes'), ('manage_banners', 'Manage Banners'), ('create_discounts', 'Create Discount Codes'), ('view_analytics', 'View Analytics'), ('view_audit_logs', 'View Audit Logs'), ('manage_settings', 'Manage System Settings'), ('access_admin_panel', 'Access Admin Panel')], max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=50)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Admin'), ('operations_admin', 'Operations Admin'), ('verification_admin', 'Verification Admin'), ('finance_admin', 'Finance Admin'), ('support_admin', 'Support Admin'), ('content_admin', 'Content Admin'), ('marketing_admin', 'Marketing Admin'), ('security_admin', 'Security Admin'), ('house_agent', 'House Agent'), ('house_owner', 'House Owner'), ('hotel_owner', 'Hotel/BnB Owner'), ('taxi_provider', 'Taxi Provider'), ('tour_provider', 'Tour/Package Provider'), ('customer', 'Customer')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_admin_role', models.BooleanField(default=False)),
                ('is_partner_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('business_license', 'Business License'), ('tax_certificate', 'Tax Certificate'), ('property_deed', 'Property Deed/Title'), ('lease_agreement', 'Lease Agreement'), ('driver_license', 'Driver License'), ('vehicle_registration', 'Vehicle Registration'), ('insurance', 'Insurance Certificate'), ('other', 'Other Document')], max_length=30)),
                ('file', models.FileField(upload_to='verification_documents/%Y/%m/')),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='roles.partnerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='roles.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='roles.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='roles.role')),
            ],
            options={
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
