# Generated by Django 4.2.30 on 2026-05-14 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0009_property_base_currency_property_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('home_banner', 'Home Page Banner'), ('search_sidebar', 'Search Sidebar'), ('detail_page', 'Property Detail Page'), ('packages_top', 'Packages Page Top')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('cta_label', models.CharField(default='Learn more', max_length=60)),
                ('cta_url', models.URLField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('background_color', models.CharField(blank=True, default='', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('partner_type', models.CharField(choices=[('ride_hail', 'Ride Hailing'), ('airport', 'Airport Transfer'), ('local', 'Local Transport'), ('shuttle', 'Shared Shuttle'), ('luxury', 'Luxury Chauffeur')], default='ride_hail', max_length=20)),
                ('countries', models.JSONField(default=list, help_text='ISO-2 country codes where this partner operates')),
                ('icon', models.CharField(default='🚕', help_text='Emoji icon for the partner', max_length=10)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('color', models.CharField(default='#1f2933', help_text='Brand hex color for UI', max_length=20)),
                ('referral_url', models.URLField(help_text='Base URL or affiliate link for this partner')),
                ('deep_link_template', models.TextField(blank=True, default='', help_text='Deep link URL template. Use {lat}, {lng}, {name}, {address} placeholders. Leave blank to use referral_url as-is.')),
                ('tagline', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.PositiveIntegerField(blank=True, null=True)),
                ('property_location', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=10)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='monetization.transportpartner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic (KES 1,000/mo)'), ('premium', 'Premium (KES 5,000/mo)'), ('spotlight', 'Spotlight (KES 15,000/mo)')], default='basic', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_campaigns', to='properties.property')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
