# Generated by Django 4.2.30 on 2026-05-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_status',
            field=models.CharField(choices=[('active', 'Active'), ('warning', 'Warning (30d overdue)'), ('limited', 'Limited Visibility (60d overdue)'), ('restricted', 'Restricted (90d overdue)'), ('suspended', 'Suspended')], default='active', help_text='Enforced automatically by the billing system based on overdue commissions.', max_length=20),
        ),
    ]
